<<<<<<< HEAD
# Generated by Django 4.1.7 on 2023-03-16 08:36
=======
# Generated by Django 4.1.7 on 2023-03-16 09:23
>>>>>>> 39e3a9e426048d3c8639a1965bc843f9d5ff6ee9

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

<<<<<<< HEAD
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("cancellation", models.BooleanField()),
                ("Date", models.DateField()),
=======
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brief', models.CharField(max_length=50)),
>>>>>>> 39e3a9e426048d3c8639a1965bc843f9d5ff6ee9
            ],
        ),
    ]
