# Generated by Django 4.1.7 on 2023-03-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood', models.CharField(max_length=100)),
                ('cpr', models.CharField(max_length=100)),
                ('height', models.FloatField(max_length=5)),
                ('weight', models.FloatField(max_length=5)),
                ('dof', models.DateField(max_length=100)),
                ('sensitivity', models.TextField(max_length=5000)),
            ],
        ),
    ]
